[package]
name = "arc"
version = "0.1.0"
authors = ["Jesse Gibson <JesseTheGibson@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
reqwest = "0.9.20"
serde = "1.0.101"
